### ISSUE TITLE
CUDA error in pointnet2

### ISSUE THREAD

**Issue by elevenjiang1** [OCRTOC/OCRTOC_software_package#8]
I can not run the baseline test for CUDA error in pointnet2;I guess maybe because I run on GTX1060 but driver is too high?

**Error happen in roslaunch ocrtoc_task solution.launch  After robot arm move around the desk,the error happen,in Graspnet infer forward.I also test grouped_xyz_ = torch.matmul(grouped_xyz_, rot) singly,and it is good**
```
import torch

A=torch.randn((1,1024,64,3))
B=torch.randn((1,1024,3,4))

out=torch.matmul(A,B)
print("out shape:")
print(out.shape)
```

**Error code is:**
[INFO] [1633087308.864957, 102.472000]: Get a joint space goal:
[INFO] [1633087308.865770, 102.472000]: joint_goal: [1.4834139747315818, -0.22268014487058366, -0.1985030742800026, -2.412410026148746, -0.6452087935672866, 1.5152949988444642, 0.08003010758840406]
[ INFO] [1633087308.875540450, 102.496000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1633087308.875615357, 102.496000000]: Planning attempt 1 of at most 1
[ INFO] [1633087308.875970141, 102.500000000]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1633087308.876096994, 102.500000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1633087308.887386082, 102.504000000]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1633087308.887415557, 102.504000000]: Solution found in 0.011376 seconds
[ INFO] [1633087308.892055194, 102.528000000]: SimpleSetup: Path simplification took 0.004602 seconds and changed from 4 to 2 states
[ INFO] [1633087316.757148009, 110.360000000]: Controller position_joint_trajectory_controller successfully finished
[ INFO] [1633087316.814564999, 110.452000000]: Completed trajectory execution with status SUCCEEDED ...
[ INFO] [1633087316.824338807, 110.464000000]: Received event 'stop'
[INFO] [1633087316.824329, 110.464000]: Done.
[INFO] [1633087316.826438, 110.464000]: Finish joint space goal:[ 1.48341397 -0.22268014 -0.19850307 -2.41241003 -0.64520879  1.515295
  0.08003011]
[ERROR] [1633087333.753505, 127.272000]: Error processing request: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 632, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/scripts/perception_server.py", line 43, in perception_target_handler\n    object_list = request.target_object_list,\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/perceptor.py", line 471, in get_response\n    pose_method = self.config[\'pose_method\']\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/perceptor.py", line 439, in percept\n    gg = self.compute_grasp_pose(full_pcd)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/perceptor.py", line 300, in compute_grasp_pose\n    gg = self.graspnet_baseline.inference(grasp_pcd)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/graspnet_baseline.py", line 91, in inference\n    gg = self.get_grasps(end_points)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/graspnet_baseline.py", line 80, in get_grasps\n    end_points = self.net(end_points)\n', '  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl\n    result = self.forward(*input, **kwargs)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/models/graspnet.py", line 68, in forward\n    end_points = self.grasp_generator(end_points)\n', '  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl\n    result = self.forward(*input, **kwargs)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/models/graspnet.py", line 51, in forward\n    vp_features = self.crop(seed_xyz, pointcloud, grasp_top_views_rot)\n', '  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl\n    result = self.forward(*input, **kwargs)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/models/modules.py", line 129, in forward\n    pointcloud, seed_xyz, vp_rot\n', '  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl\n    result = self.forward(*input, **kwargs)\n', '  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/pointnet2/pointnet2_utils.py", line 529, in forward\n    grouped_xyz_ = torch.matmul(grouped_xyz_, rot)\n', 'RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`\n']
[ERROR] [1633087333.755645, 127.272000]: Exception in your execute callback: service [/perception_action_target] responded with an error: error processing request: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/root/ocrtoc_ws/src/ocrtoc_planning/scripts/solution_entrance.py", line 32, in execute_callback
    self.planner.cycle_plan_all()
  File "/root/ocrtoc_ws/src/ocrtoc_planning/scripts/task_planning.py", line 370, in cycle_plan_all
    self.get_pose_perception(left_object_dic.keys())  # get pose from perception
  File "/root/ocrtoc_ws/src/ocrtoc_planning/scripts/task_planning.py", line 122, in get_pose_perception
    perception_result = self._service_get_target_pose(request_msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 522, in call
    responses = transport.receive_once()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 735, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 360, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 343, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
ServiceException: service [/perception_action_target] responded with an error: error processing request: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

![Screenshot from 2021-10-01 19-29-30](https://user-images.githubusercontent.com/43636049/135612841-0351915d-0d28-42af-b2c6-7a39ee7d448f.png)

**Comment by elevenjiang1** [comment]
After upgrade torch from 1.8 to 1.9,This problem solved~

**Comment by DCNSW** [comment]
I have the same issue, but after upgrade torch from 1.8 to 1.9 by using the command
`pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio===0.9.1 -f https://download.pytorch.org/whl/torch_stable.html`

I get another error about import of pointnet:
`  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/models/backbone.py", line 14, in <module>
    from ..pointnet2.pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/root/ocrtoc_ws/src/ocrtoc_perception/src/ocrtoc_perception/graspnet/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst`

Run on GTX1080, have you got the same error?  @elevenjiang1 @GouMinghao

**Comment by DCNSW** [comment]
Thank you, it helps a lot.
